<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>BR</name>
  <uuid>97d7485b-1db3-4ee0-bf51-5d121021762e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is  "Hello"
then
	set decision to "Hi" ;
    else
   
    set decision to "Bye";
    ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
